### ISSUE TITLE
Fix `home_page_test.dart` in GitHub actions

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1186]
**Describe the bug**
Our PR Github Actions for testing the code base pass, but we have a warning error that we should fix to make sure everything works as expected.

**To Reproduce**

1. Submit PR
2. The `Testing Codebase` -> `Testing Codebase` part of the GitHub actions displays the screenshot error

Alternatively you can [review all past GitHub actions for all historical PRs on the Actions tab for the repository](https://github.com/PalisadoesFoundation/talawa/actions).

**Expected behavior**
No error

**Actual behavior**
See error in screenshot and below
```
 01:13 +54: /home/runner/work/talawa/talawa/test/widget_tests/home_page_test.dart: HomePage Widget Test Testing if Events Screen Shows up                                                               
01:13 +54: /home/runner/work/talawa/talawa/test/widget_tests/home_page_test.dart: HomePage Widget Test Testing if Events Screen Shows up                                                               
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
The finder "zero widgets with icon "IconData(U+0E241)" (ignoring offstage widgets)" (used in a call
to "tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:900:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:839:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)
#3      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///home/runner/work/talawa/talawa/test/widget_tests/home_page_test.dart:79:24)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════

01:13 +55: /home/runner/work/talawa/talawa/test/widget_tests/home_page_test.dart: HomePage Widget Test Testing if Events Screen Shows up                                                               
01:13 +55: /home/runner/work/talawa/talawa/test/widget_tests/home_page_test.dart: HomePage Widget Test Testing if Post Screen Shows up   
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/152259340-b7914099-cc95-4cff-9830-3be1b3c1d698.png)

**Additional details**
N/A

**Comment by guptapriyanshu7** [comment]
@palisadoes I am working on this.

**Comment by palisadoes** [comment]
Please make sure the issue is assigned to you before creating the PR as outlined in the CONTRIBUTING.md file.
