### ISSUE TITLE
Created Events list screen Error

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#130]
The event creation is denied due to date format issue
```
E/flutter (25283): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Invalid date format
E/flutter (25283): 1619634540000
E/flutter (25283): #0      DateTime.parse (dart:core/date_time.dart:322:7)
E/flutter (25283): #1      _EventsState.getEvents.<anonymous closure>
package:talawa/…/events/events.dart:149
E/flutter (25283): #2      Sort._insertionSort (dart:_internal/sort.dart:69:36)
E/flutter (25283): #3      Sort._doSort (dart:_internal/sort.dart:58:7)
E/flutter (25283): #4      Sort.sort (dart:_internal/sort.dart:33:5)
E/flutter (25283): #5      ListMixin.sort (dart:collection/list.dart:355:10)
E/flutter (25283): #6      _EventsState.getEvents
package:talawa/…/events/events.dart:149
E/flutter (25283): <asynchronous suspension>

```

**Comment by sumitra19jha** [comment]
I am working on it.

**Comment by sumitra19jha** [comment]
Pull Request is made #136

**Comment by DeltaHarbinger** [comment]
Hey @sumitra19jha, I made a comment on your PR. You'll have to pull the most up-to-date version of master and re-implement your changes there. There were a lot of changes that conflicted with existing PRs.

**Comment by sumitra19jha** [comment]
Sure. I am working on it

**Comment by sumitra19jha** [comment]
@DeltaHarbinger I created a PR based on the very recent changes
